apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mljobs.kubeflow-mini.io
spec:
  group: kubeflow-mini.io
  names:
    kind: MLJob
    listKind: MLJobList
    plural: mljobs
    singular: mljob
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Project
          type: string
          jsonPath: .spec.project
        - name: Owner
          type: string
          jsonPath: .spec.owner
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["training", "project", "owner"]
              properties:
                # 管理信息
                jobId:
                  type: string
                  description: "任务ID"
                project:
                  type: string
                  description: "项目名称"
                owner:
                  type: string
                  description: "任务所有者"
                description:
                  type: string
                  description: "任务描述"
                tags:
                  type: array
                  description: "标签列表"
                  items:
                    type: string
                priority:
                  type: integer
                  description: "任务优先级"
                  minimum: 0
                  maximum: 100
                  default: 50
                # Training配置
                training:
                  type: object
                  description: "training-operator的任务配置"
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "任务状态"
                  enum: ["Created", "Running", "Failed", "Succeeded", "Deleted"]
                startTime:
                  type: string
                  format: date-time
                  description: "任务开始时间"
                completionTime:
                  type: string
                  format: date-time
                  description: "任务完成时间"
                duration:
                  type: string
                  description: "任务运行时长"
                conditions:
                  type: array
                  items:
                    type: object
                    required: ["type", "status", "lastTransitionTime", "reason"]
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string 