apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mljobs.kubeflow-mini.io
spec:
  group: kubeflow-mini.io
  names:
    kind: MLJob
    listKind: MLJobList
    plural: mljobs
    singular: mljob
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["training"]
              properties:
                training:
                  type: object
                  description: "training-operator的任务配置"
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "任务状态"
                  enum: ["Created", "Running", "Failed", "Succeeded", "Deleted"]
                conditions:
                  type: array
                  items:
                    type: object
                    required: ["type", "status", "lastTransitionTime", "reason"]
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string 