apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mljobs.kubeflow-mini.io
spec:
  group: kubeflow-mini.io
  names:
    kind: MLJob
    listKind: MLJobList
    plural: mljobs
    singular: mljob
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["image"]
              properties:
                type:
                  type: string
                  enum: ["pytorch"]
                  default: "pytorch"
                frameworkVersion:
                  type: string
                  default: "1.13.1"
                workerReplicas:
                  type: integer
                  minimum: 1
                  default: 1
                image:
                  type: string
                command:
                  type: array
                  items:
                    type: string 