apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-mini-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-mini-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeflow-mini-operator
  template:
    metadata:
      labels:
        app: kubeflow-mini-operator
    spec:
      serviceAccountName: kubeflow-mini-operator
      containers:
      - name: operator
        image: kubeflow-mini-operator:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        env:
        - name: WATCH_NAMESPACE
          value: ""  # Watch all namespaces
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "kubeflow-mini-operator" 