apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-mini-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-mini-operator
rules:
# MLJob资源的权限
- apiGroups: ["kubeflow-mini.io"]
  resources: ["mljobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["kubeflow-mini.io"]
  resources: ["mljobs/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["kubeflow-mini.io"]
  resources: ["mljobs/finalizers"]
  verbs: ["update"]

# Training Operator资源的权限
- apiGroups: ["kubeflow.org"]
  resources: ["pytorchjobs", "tfjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["kubeflow.org"]
  resources: ["pytorchjobs/status", "tfjobs/status"]
  verbs: ["get"]

# Kopf需要的权限
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-mini-operator
subjects:
- kind: ServiceAccount
  name: kubeflow-mini-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubeflow-mini-operator
  apiGroup: rbac.authorization.k8s.io 