apiVersion: v1
kind: Service
metadata:
  name: kubeflow-mini-backend
  namespace: default
  labels:
    app: kubeflow-mini
    component: backend
spec:
  selector:
    app: kubeflow-mini
    component: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeflow-mini-data
  namespace: default
  labels:
    app: kubeflow-mini
    component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-mini-secrets
  namespace: default
  labels:
    app: kubeflow-mini
    component: backend
type: Opaque
data:
  secret-key: "your-base64-encoded-secret-key"  # 需要替换为实际的base64编码密钥
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-mini-backend
  namespace: default
  labels:
    app: kubeflow-mini
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeflow-mini
      component: backend
  template:
    metadata:
      labels:
        app: kubeflow-mini
        component: backend
    spec:
      containers:
      - name: backend
        image: kubeflow-mini-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          value: "sqlite:///data/kubeflow_mini.db"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kubeflow-mini-secrets
              key: secret-key
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PORT
          value: "8000"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: data
          mountPath: /data
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: kubeflow-mini-data 