apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-mini-owner
rules:
# Owner资源的权限
- apiGroups: ["kubeflow-mini.io"]
  resources: ["owners", "owners/status", "owners/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-mini-owner
subjects:
- kind: ServiceAccount
  name: kubeflow-mini-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubeflow-mini-owner
  apiGroup: rbac.authorization.k8s.io 